#
# Makefile for specinvoke
# Copyright 1996-2009 Standard Performance Evaluation Corporation
#
# $Id: Makefile.nt 6361 2011-03-03 22:29:36Z cloyce $

all: specinvoke.exe specinvoke_pm.exe

CFLAGS=/Zi -Iwin32
LDFLAGS=/Zi

# If anyone ever writes a performance monitor module for Windows, put the
# name of its directory here:
PM_DIR=pm_stub

specinvoke.obj: win32\config.h specinvoke.h specinvoke.c
win32.obj: win32\config.h specinvoke.h win32.c
getopt.obj: win32\config.h getopt.c
specinvoke.exe: specinvoke.obj win32.obj getopt.obj
	$(CC) $(LDFLAGS) -Fe$@ specinvoke.obj getopt.obj win32.obj

specinvoke_pm.exe: specinvoke_pm.obj win32_pm.obj getopt.obj $(PM_DIR)\pmfuncs.obj
	$(CC) $(LDFLAGS) -Fe$@ specinvoke_pm.obj getopt.obj win32_pm.obj $(PM_DIR)\pmfuncs.obj

specinvoke_pm.obj: win32\config.h specinvoke.h specinvoke.c $(PM_DIR)\specinvoke_pm.h
	$(CC) $(CFLAGS) -c -Fo$@ -I$(PM_DIR) -DPERFMON specinvoke.c

win32_pm.obj: win32\config.h specinvoke.h win32.c $(PM_DIR)\specinvoke_pm.h
	$(CC) $(CFLAGS) -c -Fo$@ -I$(PM_DIR) -DPERFMON win32.c

$(PM_DIR)\pmfuncs.obj: $(PM_DIR)\specinvoke_pm.h
	cd $(PM_DIR)
	$(MAKE) /f Makefile.nt
	cd ..

cleanobjs:
	del *.obj $(PM_DIR)\*.obj *.ilk $(PM_DIR)\*.ilk *.pdb $(PM_DIR)\*.pdb

clean: cleanobjs
	del specinvoke.exe specinvoke_pm.exe

distclean: clean
