DYNINST_ROOT=../Dyninst-9.1.0
DYNINST_IROOT=../Dyninst-9.1.0/install-dir
#DYNINST_ROOT=../Dyninst-9.0.3
#DYNINST_IROOT=../Dyninst-9.0.3/install-dir
#DYNINST_ROOT=../dyninst-mainline
#DYNINST_IROOT=../dyninst-mainline/install-dir
DYNAMORIO_ROOT=../DynamoRIO-Linux-5.0.0-9
