PROJECT_ROOT=/home/matthias/typearmor

DYNINST_ROOT=$(PROJECT_ROOT)/Dyninst
DYNAMORIO_ROOT=$(PROJECT_ROOT)/DynamoRIO
INSTALL_DIR=$(PROJECT_ROOT)/bin

CC=gcc #clang -fsanitize=undefined
CXX=g++ #clang++ -fsanitize=undefined
ECHO=echo

